export const ENV_HOST_KEY = 'HOST';

export const ENV_PORT_KEY = 'PORT';

export const ENV_JWT_SECRET_KEY = 'JWT_SECRET';

export const ENV_DB_HOST_KEY = 'DB_HOST';

export const ENV_DB_PORT_KEY = 'DB_PORT';

export const ENV_DB_USERNAME_KEY = 'DB_USERNAME';

export const ENV_DB_PASSWORD_KEY = 'DB_PASSWORD';

export const ENV_DB_DATABASE_KEY = 'DB_DATABASE';

export const ENV_REDIS_BINDING_PORT_KEY = 'REDIS_BINDING_PORT';

export const ENV_REDIS_PORT_KEY = 'REDIS_PORT';

export const ENV_REDIS_PASSWORD_KEY = 'REDIS_PASSWORD';

export const ENV_SWAGGER_USER_KEY = 'SWAGGER_USER';

export const ENV_SWAGGER_PASSWORD_KEY = 'SWAGGER_PASSWORD';

export const ENV_ACCESS_TOKEN_EXPIRE_SECONDS = 'ACCESS_TOKEN_EXPIRE_SECONDS';

export const ENV_REFRESH_TOKEN_EXPIRE_SECONDS = 'REFRESH_TOKEN_EXPIRE_SECONDS';
